import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ReactNode} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children } : { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex layout min-h-screen items-center justify-center font-sans ">
                <Link className="absolute left-15 top-5 text-2xl hidden lg:flex" href="/">HOME</Link>
                <Link className="absolute right-15 top-5 text-2xl hidden lg:flex" href="/register">REGISTER</Link>
                <Link className="absolute right-65 top-5 text-2xl hidden lg:flex" href="/login">LOGIN</Link>
          <div className="w-170 border-1 h-150 flex flex-col justify-between items-center relative rounded-4xl ">
              <div className="opacity-70 rounded-4xl w-full h-full bg-black absolute">
              </div>
              {children}
          </div>
      </div>
      </body>
    </html>
  );
}
